appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: azure, linux_ppc64le: azure}
travis:
  secure: {BINSTAR_TOKEN: FJ2w2SEoa7ibqk31yKGwoALn0OhzBN6FigCjrY08SeJTitQP2OOoaKYgKrQ8Gte6gAbnY2aQZZEFu2bUpi9+451bOarXK24PrfKaYmrohQgSovnveBogsiqsKf7GP0AlrYZf1oLQSx1Dor6VQu4vmF2CAW09pgLAZ2UI5fy/UIoWIM5cGJVFACQxQHxxl1kBS+zhY9WBd0rkoWzCX8AR8MA04YkOjaWMhiqSCTv5rPxRY9dW9OdMHYIt3BqjnlppNFLbDYwv/qvFNWq1u8dKtOnAdjAc+PV6r44FTLTgM2X3Hs0fVWUKy2tYS1qUVdPKpiqRB5pgxtkHC/0EFjTw9aZ03l3BzrAD05+8MAW9Y88xJusc8PGJbf9b4sECYDEu5E5UAJSjsMT9l4pqHXuYOTOpTDIhpjG4PlVBCod8pRUwtykLqipsMw6TpAXDhm0GAD5Z4rcgcQxgB+aTXnYUWXLeacCCoi32eLEHUtv5TKEiOPj3iSp1jPSwt1n091TfAPIPI9XSTA0Q6IvDQ+5BuN547Uv9yRr6sIykVV2RzDWOmlqFDyZsUOKVE7dFi2dNO2cCAv+Ep1/D6y9g98l68Nn7h5sLco+MYYSefyA8YhDAIOnm5ohbaiIDMSiTjMyhy6M+V7Qc0fHMVCQLUW6kf0qyfHCApgibaxzfYb6Wqgs=}
